name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on:
            ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: set up go 1.20
              uses: actions/setup-gov4
              with:
                  go-version: 1.20
              run: go version


